name: flutter_course
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter_osm_plugin: ^0.70.4
  geolocator: ^12.0.0
  geocoding: ^2.1.1
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  http: ^1.3.0
  flutter_location_search: ^1.0.0
  http_parser: ^4.0.2
  path: ^1.8.2

  google_maps_flutter: ^2.2.0
  google_maps_flutter_web: ^0.4.0+1


  device_preview: ^1.2.0
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+5

  stomp_dart_client: ^0.4.4
  web_socket_channel: ^2.4.0
  overlay_support: ^2.0.1


dev_dependencies:
  shared_preferences: ^2.2.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/gf.jpg
    - images/gf.png
    - images/welcome_image.png
    - images/pic1.png
    - images/pic2.png
    - images/pic3.png
    - images/photo.png
    - images/no_vehicle.png
    - images/invite.png
    - images/password.png
    - images/qrcode.png
    - images/review.png
    - images/thanks.jpg
    - images/frame3.png
    - images/frame4.png
    - images/frame5.png


